deel:
  outputs:
    dev:
      account: bydspvi-id08418
      database: DEEL
      password:
      role: ACCOUNTADMIN
      schema: GLOBEPAY
      threads: 4
      type: snowflake
      user: analyticstask
      warehouse: COMPUTE_WH
  target: dev